//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlnGen {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SlnGenStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SlnGenStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SlnGen.SlnGenStrings", typeof(SlnGenStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Imports to Safe Import list in Registry.
        /// </summary>
        internal static string addSafeImportsUsage {
            get {
                return ResourceManager.GetString("addSafeImportsUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the path to the VS development environment exe (overrides VSDEVENV env var and registry key for launcher)..
        /// </summary>
        internal static string devenvUsage {
            get {
                return ResourceManager.GetString("devenvUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to turn errors on and off. Prefix name with - to turn off. &quot;none&quot;, &quot;default&quot;, and &quot;all&quot; can be used as well..
        /// </summary>
        internal static string errorUsage {
            get {
                return ResourceManager.GetString("errorUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify files and directories to operate on..
        /// </summary>
        internal static string fileUsage {
            get {
                return ResourceManager.GetString("fileUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix the tools version of the project files being loaded to correspond with the target visual studio version..
        /// </summary>
        internal static string fixToolsVersionUsage {
            get {
                return ResourceManager.GetString("fixToolsVersionUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens VS in EXP hive mode..
        /// </summary>
        internal static string hiveUsage {
            get {
                return ResourceManager.GetString("hiveUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create nested solution folders that mirror the filesystem..
        /// </summary>
        internal static string nestUsage {
            get {
                return ResourceManager.GetString("nestUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t launch VS, just create the .sln file..
        /// </summary>
        internal static string noLaunchUsage {
            get {
                return ResourceManager.GetString("noLaunchUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t skip referenced projects with ReferenceOutputAssembly set to False..
        /// </summary>
        internal static string noSkipRefsUsage {
            get {
                return ResourceManager.GetString("noSkipRefsUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the output file name (overrides /w)..
        /// </summary>
        internal static string outputUsage {
            get {
                return ResourceManager.GetString("outputUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes temporary files created by slngen..
        /// </summary>
        internal static string purgeUsage {
            get {
                return ResourceManager.GetString("purgeUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiet: don&apos;t print warnings about projects..
        /// </summary>
        internal static string quietUsage {
            get {
                return ResourceManager.GetString("quietUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurse on the specified directory..
        /// </summary>
        internal static string recurseUsage {
            get {
                return ResourceManager.GetString("recurseUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build and run the current project inside VS..
        /// </summary>
        internal static string runUsage {
            get {
                return ResourceManager.GetString("runUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Location-Based Source Control..
        /// </summary>
        internal static string sourceDepotUsage {
            get {
                return ResourceManager.GetString("sourceDepotUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the new .sln file in the current directory..
        /// </summary>
        internal static string useCurrentUsage {
            get {
                return ResourceManager.GetString("useCurrentUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do additional validation checks on a group of projects..
        /// </summary>
        internal static string validateUsage {
            get {
                return ResourceManager.GetString("validateUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbosely describe what is happening..
        /// </summary>
        internal static string verboseUsage {
            get {
                return ResourceManager.GetString("verboseUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run VSMSBuild instead of VS.
        /// </summary>
        internal static string vsmsbuildUsage {
            get {
                return ResourceManager.GetString("vsmsbuildUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the version of VS to use (default is autodetect from highest version)..
        /// </summary>
        internal static string vsverUsage {
            get {
                return ResourceManager.GetString("vsverUsage", resourceCulture);
            }
        }
    }
}
